name: 'semver-releaser'
description: 'Creates SemVer releases based on Conventional Commits'
branding:
  icon: box
  color: yellow
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  push:
    description: 'Whether to push a new tag for the calculated version'
    required: false
    default: 'true'
  rules:
    description: 'How to handle prefixes'
    required: false
    default: 'fix=patch feat=minor bang=major'
  categories:
    description: 'How to generate categories based on prefixes'
    required: false
    default: 'fix=Fix feat=Feature'
  ignore:
    description: "A space-delimited list of prefixes to ignore"
    required: false
    default: ""
outputs:
  version:
    description: 'Version tagged and pushed'
runs:
  using: 'docker'
  image: docker://ghcr.io/heyvito/semver-releaser:latest
  args:
    - "--token=${{ inputs.github-token }}"
    - "--push=${{ inputs.push }}"
    - "--rules=${{ inputs.rules }}"
    - "--categories=${{ inputs.categories }}"
    - "--ignore=${{ inputs.ignore }}"
